Update newtonsoftjson (#160)
* update Newtonsoft.Json reference to 13.0.1

Closes https://github.com/G-Research/consuldotnet/issues/159

* Reference Microsoft.CSharp for all targets

Fixes error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.Binder.Convert'