Test: fix intermittent failing test by increasing timeout
Error: Consul.Test.SemaphoreTest.Semaphore_OneShot: System.InvalidOperationException : Failed to create session
  Failed Consul.Test.SemaphoreTest.Semaphore_OneShot [365 ms]
  Error Message:
   System.InvalidOperationException : Failed to create session
---- Consul.ConsulRequestException : Unexpected response, status code InternalServerError: Missing node registration
  Stack Trace:
     at Consul.Semaphore.Acquire(CancellationToken ct) in D:\a\consuldotnet\consuldotnet\Consul\Semaphore.cs:line 343
   at Consul.Semaphore.Acquire(CancellationToken ct) in D:\a\consuldotnet\consuldotnet\Consul\Semaphore.cs:line 456
   at Consul.Test.SemaphoreTest.Semaphore_OneShot() in D:\a\consuldotnet\consuldotnet\Consul.Test\SemaphoreTest.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at Consul.PutRequest`2.Execute(CancellationToken ct) in D:\a\consuldotnet\consuldotnet\Consul\Client_PutRequests.cs:line 352
   at Consul.Session.Create(SessionEntry se, WriteOptions q, CancellationToken ct) in D:\a\consuldotnet\consuldotnet\Consul\Session.cs:line 296
   at Consul.Semaphore.CreateSession() in D:\a\consuldotnet\consuldotnet\Consul\Semaphore.cs:line 668
   at Consul.Semaphore.Acquire(CancellationToken ct) in D:\a\consuldotnet\consuldotnet\Consul\Semaphore.cs:line 337